services:
  db:
    image: mysql:8.4
    container_name: ecommerce-mysql
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    healthcheck:
      test:	["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: