server:
  port: ${PORT:8080}   # Render等のPaaSでも動くように
  address: 0.0.0.0
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ecommerce-product
    access-expires: 60
    refresh-expires: 7